const productsStok = [
    {
        productId: 0,
        class: "waterproof",
        type: "Waterproof Men",
        price: 399,
        units: 10,
        photo: `<img src="images/raincoat-1245688_1920.jpg" alt= "A person wearing a red raincoat" class="spotlightImage">`,
        waterproof: "10.000 mm",
        minTemp: "-3",
        hoursOut: 10,
        bestseller: false,
    },
    {
        productId: 1,
        class: "waterproof",
        type: "Waterproof Unisex",
        price: 399,
        units: 10,
        photo: `<img src="images/raincoat-1245688_1920.jpg" alt= "A person wearing a red raincoat" class="spotlightImage">`,
        waterproof: "10.000 mm",
        minTemp: "-3",
        hoursOut: 10,
        bestseller: false,
    },
    {
        productId: 2,
        class: "waterproof",
        type: "Waterproof Woman",
        price: 399,
        units: 10,
        photo: `<img src="images/karsten-winegeart-jVT8vo04UT0-unsplash.jpg" alt="A woman wearing a yellow raincoat at the top of a cliff" class="spotlightImage">`,
        waterproof: "10.000 mm",
        minTemp: "-3",
        hoursOut: 10,
        bestseller: true,
    },
    {
        productId: 3,
        class: "skiSnowboard",
        type: "Ski & Snowboard Men",
        price: 599,
        units: 5,
        photo: `<img src="images/simon-berger-PcVqr8v4XaA-unsplash.jpg" alt="A person skiing wearing a winter jacket" class="spotlightImage">`,
        waterproof: "5.000 mm",
        minTemp: "-20",
        hoursOut: 3,
        bestseller: false,
    },
    {
        productId: 4,
        class: "skiSnowboard",
        type: "Ski & Snowboard Unisex",
        price: 599,
        units: 5,
        photo: `<img src="images/simon-berger-PcVqr8v4XaA-unsplash.jpg" alt="A person skiing wearing a winter jacket" class="spotlightImage">`,
        waterproof: "5.000 mm",
        minTemp: "-20",
        hoursOut: 3,
        bestseller: false,
    },
    {
        productId: 5,
        class: "skiSnowboard",
        type: "Ski & Snowboard Woman",
        price: 599,
        units: 5,
        photo: `<img src="images/simon-berger-PcVqr8v4XaA-unsplash.jpg" alt="A person skiing wearing a winter jacket" class="spotlightImage">`,
        waterproof: "5.000 mm",
        minTemp: "-20",
        hoursOut: 3,
        bestseller: false,
    },
    {
        productId: 6,
        class: "windbreaker",
        type: "Windbreaker Men",
        price: 299,
        units: 15,
        photo: `<img src="images/joshua-earle-ICE__bo2Vws-unsplash.jpg" alt="A men wearing a hooded jacket on a beach" class="spotlightImage">`,
        waterproof: "7.000 mm",
        maxWind: "10 m/s",
        minTemp: "+10",
        hoursOut: 3,
        bestseller: true,
    },
    {
        productId: 7,
        class: "windbreaker",
        type: "Windbreaker Unisex",
        price: 299,
        units: 15,
        photo: `<img src="images/joshua-earle-ICE__bo2Vws-unsplash.jpg" alt="A men wearing a hooded jacket on a beach" class="spotlightImage">`,
        waterproof: "7.000 mm",
        maxWind: "10 m/s",
        minTemp: "+10",
        hoursOut: 3,
        bestseller: false,
    },
    {
        productId: 8,
        class: "windbreaker",
        type: "Windbreaker Woman",
        price: 299,
        units: 15,
        photo: `<img src="images/joshua-earle-ICE__bo2Vws-unsplash.jpg" alt="A men wearing a hooded jacket on a beach" class="spotlightImage">`,
        waterproof: "7.000 mm",
        maxWind: "10 m/s",
        minTemp: "+10",
        hoursOut: 3,
        bestseller: false,
    },
    {
        productId: 9,
        class: "accessories",
        type: "Accessories Men",
        price: 99,
        units: 20,
        photo: `<img src="images/roberto-martinez-WBgPMst9toY-unsplash.jpg" alt = "A sewing workplace" class="spotlightImage">`,
        bestseller: false,
    },
    {
        productId: 10,
        class: "accessories",
        type: "Accessories Unisex",
        price: 99,
        units: 20,
        photo: `<img src="images/roberto-martinez-WBgPMst9toY-unsplash.jpg" alt = "A sewing workplace" class="spotlightImage">`,
        bestseller: true,
    },
    {
        productId: 11,
        class: "accessories",
        type: "Accessories Woman",
        price: 99,
        units: 20,
        photo: `<img src="images/roberto-martinez-WBgPMst9toY-unsplash.jpg" alt = "A sewing workplace" class="spotlightImage">`,
        bestseller: false,
    },
];